//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitgliederverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Members = new HashSet<Member>();
            this.Members1 = new HashSet<Member>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Member> Members1 { get; set; }
    }
}
