//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitgliederverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFunction
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> FunctionID { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Member Member { get; set; }
    }
}
