//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitgliederverwaltung.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.MemberFunctions = new HashSet<MemberFunction>();
        }
    
        public int ID { get; set; }
        public string LastName { get; set; }
        public string ForeName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Street { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CityID { get; set; }
        public string TelefonNumber1 { get; set; }
        public string TelefonNumber2 { get; set; }
        public string TelefonNumber3 { get; set; }
        public string EMail { get; set; }
        public string HealthInsuranceNumber { get; set; }
        public Nullable<System.DateTime> DateOfClubEntry { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> Class2ID { get; set; }
        public string Note { get; set; }
    
        public virtual City City { get; set; }
        public virtual Class Class { get; set; }
        public virtual Class Class1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<MemberFunction> MemberFunctions { get; set; }
    }
}
